server:
  port: 8094

spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3307/test?serverTimezone=Asia/Shanghai
      username: root
      password: 123456
    postgresql:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/test
      username: postgres
      password: root
    timescaledb:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/timescaledb
      username: postgres
      password: root
  jpa:
    mysql:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    postgresql:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false
